/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentsList: typeof import('./src/components/board/CommentsList.vue')['default']
    CountLabel: typeof import('./src/components/profile/CountLabel.vue')['default']
    CreateCommentForm: typeof import('./src/components/board/CreateCommentForm.vue')['default']
    CreatePostForm: typeof import('./src/components/board/CreatePostForm.vue')['default']
    CustomHeader: typeof import('./src/components/common/CustomHeader.vue')['default']
    Forbidden: typeof import('./src/components/error/Forbidden.vue')['default']
    FreePostList: typeof import('./src/components/board/FreePostList.vue')['default']
    InsertTextForm: typeof import('./src/components/sign/InsertTextForm.vue')['default']
    InternalServerError: typeof import('./src/components/error/InternalServerError.vue')['default']
    Layout: typeof import('./src/components/common/Layout.vue')['default']
    NoContent: typeof import('./src/components/error/NoContent.vue')['default']
    NotFound: typeof import('./src/components/error/NotFound.vue')['default']
    PageBreadcrumb: typeof import('./src/components/common/PageBreadcrumb.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchActionBar: typeof import('./src/components/common/SearchActionBar.vue')['default']
    UpdateProfileForm: typeof import('./src/components/profile/UpdateProfileForm.vue')['default']
  }
}
