/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/board/CreateFreePostPage': RouteRecordInfo<'/board/CreateFreePostPage', '/board/CreateFreePostPage', Record<never, never>, Record<never, never>>,
    '/board/FreePostDetailPage': RouteRecordInfo<'/board/FreePostDetailPage', '/board/FreePostDetailPage', Record<never, never>, Record<never, never>>,
    '/board/FreePostPage': RouteRecordInfo<'/board/FreePostPage', '/board/FreePostPage', Record<never, never>, Record<never, never>>,
    '/error/ForbiddenPage': RouteRecordInfo<'/error/ForbiddenPage', '/error/ForbiddenPage', Record<never, never>, Record<never, never>>,
    '/error/InternalServerErrorPage': RouteRecordInfo<'/error/InternalServerErrorPage', '/error/InternalServerErrorPage', Record<never, never>, Record<never, never>>,
    '/error/NoContentPage': RouteRecordInfo<'/error/NoContentPage', '/error/NoContentPage', Record<never, never>, Record<never, never>>,
    '/error/NotFoundPage': RouteRecordInfo<'/error/NotFoundPage', '/error/NotFoundPage', Record<never, never>, Record<never, never>>,
    '/profile/UpdateProfilePage': RouteRecordInfo<'/profile/UpdateProfilePage', '/profile/UpdateProfilePage', Record<never, never>, Record<never, never>>,
    '/profile/UserProfilePage': RouteRecordInfo<'/profile/UserProfilePage', '/profile/UserProfilePage', Record<never, never>, Record<never, never>>,
    '/sign/SignInPage': RouteRecordInfo<'/sign/SignInPage', '/sign/SignInPage', Record<never, never>, Record<never, never>>,
    '/sign/SignUpPage': RouteRecordInfo<'/sign/SignUpPage', '/sign/SignUpPage', Record<never, never>, Record<never, never>>,
  }
}
